# Generated by Django 5.1.4 on 2025-01-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_user_options_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Technicien', 'Technicien'), ('Manager', 'Manager'), ('DGA', 'DGA')], max_length=50, verbose_name='User Role'),
        ),
    ]
