# Generated by Django 5.1.1 on 2024-10-18 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park', '0002_commissariat_etatcivil_prefecture_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_equipement', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type_eq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.typeequipement'),
        ),
    ]
