# Generated by Django 5.1.1 on 2024-09-16 21:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Serial Number')),
                ('type_eq', models.CharField(max_length=30, verbose_name='Equipment Type')),
                ('brand', models.CharField(max_length=50, verbose_name='Brand')),
                ('modele_eq', models.CharField(max_length=50, verbose_name='Model')),
                ('purchase_date', models.DateField(verbose_name='Purchase Date')),
                ('warranty_expire', models.DateField(verbose_name='Warranty Expiry Date')),
                ('status', models.CharField(choices=[('travail', 'Travail'), ('en_reparation', 'En reparation'), ('hors_service', 'Hors Service'), ('panne', 'En panne')], default='working', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('date_performed', models.DateField(default=django.utils.timezone.now)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.equipment')),
            ],
            options={
                'verbose_name': 'AuditLog',
                'verbose_name_plural': 'AuditLogs',
            },
        ),
        migrations.CreateModel(
            name='EquipmentMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateField(default=django.utils.timezone.now)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.equipment')),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='park.location')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_location', to='park.location')),
            ],
            options={
                'verbose_name': 'EquipmentMovement',
                'verbose_name_plural': 'EquipmentMovements',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(default=django.utils.timezone.now)),
                ('issue_description', models.TextField()),
                ('action_taken', models.TextField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='park.equipment')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
            },
        ),
    ]
